<?php
    $jokes = [
        'Why did the scarecrow win an award? Because he was outstanding in his field!',
        'What do you call a bear with no teeth? A gummy bear!',
        'I used to play piano by ear, but now I use my hands.',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'What did one wall say to the other wall? I’ll meet you at the corner!',
        'How do you organize a space party? You "planet"!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'Parallel lines have so much in common. It’s a shame they’ll never meet.',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How do you organize a fantastic space party? You "planet" carefully!',
        'I would tell you a joke about construction, but I’m still working on it!',
        'What do you call a fish with no eyes? Fsh!',
        'What do you get when you cross a snowman and a vampire? Frostbite!',
        'Why don’t skeletons fight each other? They don’t have the guts!',
        'I asked the librarian if they had any books on paranoia. She whispered, "They’re right behind you!"',
        'What do you call a fake noodle? An impasta!',
        'Why did the scarecrow become a successful politician? Because he was outstanding in his field!',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'How do you make holy water? You boil the hell out of it!',
        'What do you get when you cross a snowman and a dog? Frostbite!',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How does a penguin build its house? Igloos it together!',
        'Why did the scarecrow win an award? Because he was outstanding in his field!',
        'What do you call a bear with no teeth? A gummy bear!',
        'I used to play piano by ear, but now I use my hands.',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'What did one wall say to the other wall? I’ll meet you at the corner!',
        'How do you organize a space party? You "planet"!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'Parallel lines have so much in common. It’s a shame they’ll never meet.',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How do you organize a fantastic space party? You "planet" carefully!',
        'I would tell you a joke about construction, but I’m still working on it!',
        'What do you call a fish with no eyes? Fsh!',
        'What do you get when you cross a snowman and a vampire? Frostbite!',
        'Why don’t skeletons fight each other? They don’t have the guts!',
        'I asked the librarian if they had any books on paranoia. She whispered, "They’re right behind you!"',
        'What do you call a fake noodle? An impasta!',
        'Why did the scarecrow become a successful politician? Because he was outstanding in his field!',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'How do you make holy water? You boil the hell out of it!',
        'What do you get when you cross a snowman and a dog? Frostbite!',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How does a penguin build its house? Igloos it together!',
        'Why did the scarecrow win an award? Because he was outstanding in his field!',
        'What do you call a bear with no teeth? A gummy bear!',
        'I used to play piano by ear, but now I use my hands.',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'What did one wall say to the other wall? I’ll meet you at the corner!',
        'How do you organize a space party? You "planet"!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'Parallel lines have so much in common. It’s a shame they’ll never meet.',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How do you organize a fantastic space party? You "planet" carefully!',
        'I would tell you a joke about construction, but I’m still working on it!',
        'What do you call a fish with no eyes? Fsh!',
        'What do you get when you cross a snowman and a vampire? Frostbite!',
        'Why don’t skeletons fight each other? They don’t have the guts!',
        'I asked the librarian if they had any books on paranoia. She whispered, "They’re right behind you!"',
        'What do you call a fake noodle? An impasta!',
        'Why did the scarecrow become a successful politician? Because he was outstanding in his field!',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'How do you make holy water? You boil the hell out of it!',
        'What do you get when you cross a snowman and a dog? Frostbite!',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How does a penguin build its house? Igloos it together!',
        'Why did the scarecrow win an award? Because he was outstanding in his field!',
        'What do you call a bear with no teeth? A gummy bear!',
        'I used to play piano by ear, but now I use my hands.',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'What did one wall say to the other wall? I’ll meet you at the corner!',
        'How do you organize a space party? You "planet"!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'Parallel lines have so much in common. It’s a shame they’ll never meet.',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How do you organize a fantastic space party? You "planet" carefully!',
        'I would tell you a joke about construction, but I’m still working on it!',
        'What do you call a fish with no eyes? Fsh!',
        'What do you get when you cross a snowman and a vampire? Frostbite!',
        'Why don’t skeletons fight each other? They don’t have the guts!',
        'I asked the librarian if they had any books on paranoia. She whispered, "They’re right behind you!"',
        'What do you call a fake noodle? An impasta!',
        'Why did the scarecrow become a successful politician? Because he was outstanding in his field!',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'How do you make holy water? You boil the hell out of it!',
        'What do you get when you cross a snowman and a dog? Frostbite!',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How does a penguin build its house? Igloos it together!',
    ];
?>