<?php
    $jokes = [
        'Why did the scarecrow win an award? Because he was outstanding in his field!',
        'What do you call a bear with no teeth? A gummy bear!',
        'I used to play piano by ear, but now I use my hands.',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'What did one wall say to the other wall? I’ll meet you at the corner!',
        'How do you organize a space party? You "planet"!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'Parallel lines have so much in common. It’s a shame they’ll never meet.',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How do you organize a fantastic space party? You "planet" carefully!',
        'I would tell you a joke about construction, but I’m still working on it!',
        'What do you call a fish with no eyes? Fsh!',
        'What do you get when you cross a snowman and a vampire? Frostbite!',
        'Why don’t skeletons fight each other? They don’t have the guts!',
        'I asked the librarian if they had any books on paranoia. She whispered, "They’re right behind you!"',
        'What do you call a fake noodle? An impasta!',
        'Why did the scarecrow become a successful politician? Because he was outstanding in his field!',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'How do you make holy water? You boil the hell out of it!',
        'What do you get when you cross a snowman and a dog? Frostbite!',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How does a penguin build its house? Igloos it together!',
        'Why did the scarecrow win an award? Because he was outstanding in his field!',
        'What do you call a bear with no teeth? A gummy bear!',
        'I used to play piano by ear, but now I use my hands.',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'What did one wall say to the other wall? I’ll meet you at the corner!',
        'How do you organize a space party? You "planet"!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'Parallel lines have so much in common. It’s a shame they’ll never meet.',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How do you organize a fantastic space party? You "planet" carefully!',
        'I would tell you a joke about construction, but I’m still working on it!',
        'What do you call a fish with no eyes? Fsh!',
        'What do you get when you cross a snowman and a vampire? Frostbite!',
        'Why don’t skeletons fight each other? They don’t have the guts!',
        'I asked the librarian if they had any books on paranoia. She whispered, "They’re right behind you!"',
        'What do you call a fake noodle? An impasta!',
        'Why did the scarecrow become a successful politician? Because he was outstanding in his field!',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'How do you make holy water? You boil the hell out of it!',
        'What do you get when you cross a snowman and a dog? Frostbite!',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How does a penguin build its house? Igloos it together!',
        'Why did the scarecrow win an award? Because he was outstanding in his field!',
        'What do you call a bear with no teeth? A gummy bear!',
        'I used to play piano by ear, but now I use my hands.',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'What did one wall say to the other wall? I’ll meet you at the corner!',
        'How do you organize a space party? You "planet"!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'Parallel lines have so much in common. It’s a shame they’ll never meet.',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How do you organize a fantastic space party? You "planet" carefully!',
        'I would tell you a joke about construction, but I’m still working on it!',
        'What do you call a fish with no eyes? Fsh!',
        'What do you get when you cross a snowman and a vampire? Frostbite!',
        'Why don’t skeletons fight each other? They don’t have the guts!',
        'I asked the librarian if they had any books on paranoia. She whispered, "They’re right behind you!"',
        'What do you call a fake noodle? An impasta!',
        'Why did the scarecrow become a successful politician? Because he was outstanding in his field!',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'How do you make holy water? You boil the hell out of it!',
        'What do you get when you cross a snowman and a dog? Frostbite!',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How does a penguin build its house? Igloos it together!',
        'Why did the scarecrow win an award? Because he was outstanding in his field!',
        'What do you call a bear with no teeth? A gummy bear!',
        'I used to play piano by ear, but now I use my hands.',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'What did one wall say to the other wall? I’ll meet you at the corner!',
        'How do you organize a space party? You "planet"!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'Parallel lines have so much in common. It’s a shame they’ll never meet.',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How do you organize a fantastic space party? You "planet" carefully!',
        'I would tell you a joke about construction, but I’m still working on it!',
        'What do you call a fish with no eyes? Fsh!',
        'What do you get when you cross a snowman and a vampire? Frostbite!',
        'Why don’t skeletons fight each other? They don’t have the guts!',
        'I asked the librarian if they had any books on paranoia. She whispered, "They’re right behind you!"',
        'What do you call a fake noodle? An impasta!',
        'Why did the scarecrow become a successful politician? Because he was outstanding in his field!',
        'Why don’t scientists trust atoms? Because they make up everything!',
        'Why did the math book look sad? Because it had too many problems!',
        'Why did the tomato turn red? Because it saw the salad dressing!',
        'How do you make holy water? You boil the hell out of it!',
        'What do you get when you cross a snowman and a dog? Frostbite!',
        'Why did the bicycle fall over? Because it was two-tired!',
        'How does a penguin build its house? Igloos it together!',
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "What do you call a bear with no teeth? A gummy bear!",
        "I used to play piano by ear, but now I use my hands.",
        "Why don’t scientists trust atoms? Because they make up everything!",
        "Why did the math book look sad? Because it had too many problems!",
        "What did one wall say to the other wall? I’ll meet you at the corner!",
        "How do you organize a space party? You 'planet'!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "Parallel lines have so much in common. It’s a shame they’ll never meet.",
        "Why did the bicycle fall over? Because it was two-tired!",
        "How do you organize a fantastic space party? You 'planet' carefully!",
        "I would tell you a joke about construction, but I’m still working on it!",
        "What do you call a fish with no eyes? Fsh!",
        "What do you get when you cross a snowman and a vampire? Frostbite!",
        "Why don’t skeletons fight each other? They don’t have the guts!",
        "I asked the librarian if they had any books on paranoia. She whispered, 'They’re right behind you!'",
        "What do you call a fake noodle? An impasta!",
        "Why did the scarecrow become a successful politician? Because he was outstanding in his field!",
        "Why don’t scientists trust atoms? Because they make up everything!",
        "Why did the math book look sad? Because it had too many problems!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "How do you make holy water? You boil the hell out of it!",
        "What do you get when you cross a snowman and a dog? Frostbite!",
        "Why did the bicycle fall over? Because it was two-tired!",
        "How does a penguin build its house? Igloos it together!",
        "Why did the scarecrow become a stand-up comedian? Because he had a great sense of humor!",
        "Did you hear about the cheese factory that exploded? There was nothing left but de-brie!",
        "How does a barber make phone calls? He uses a clipper.",
        "What did one ocean say to the other ocean? Nothing, they just waved.",
        "Why did the tomato turn green? Because it saw the salad dressing and got jealous!",
        "How do you organize a space party on the moon? You 'meteor' expectations!",
        "Why did the computer catch a cold? It had too many windows open!",
        "What's a vampire's favorite fruit? A blood orange.",
        "I told my wife she was drawing her eyebrows too high. She looked surprised.",
        "What do you call a group of musical whales? An orca-stra!",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
        "What's a skeleton's least favorite room in the house? The living room!",
        "Why don't scientists trust stairs? Because they're always up to something.",
        "Why did the scarecrow break up with the cornstalk? He was tired of being stalked.",
        "How do you organize a space party on Mars? You 'rocket'!",
        "What do you call a bear that's stuck in the rain? A drizzly bear.",
        "What do you call a group of musical whales playing jazz? An orca-stra with some killer whale notes!",
        "Did you hear about the cheese that saved a bunch of mice? It was a real gouda Samaritan.",
        "Why did the math book look happy? Because it solved all its problems!",
        "How do you catch a squirrel? Climb a tree and act like a nut!",
        "Why don't scientists trust atoms anymore? Because they found out they make up dark matter too!",
        "What's a cow's favorite instrument? The moo-sical instrument.",
        "Why did the scarecrow win an award for bravery? Because he was outstanding in his field, even in a tornado!",
        "How do you organize a space party on Venus? You 'venus' guests and hope they arrive in one piece!",
        "What did one wall say to the other wall in a scary movie? 'I'll meet you in the dark corner!'",
        "Why don't oysters donate to charity? Because they are shellfish!",
        "What do you call a bear that's stuck in the rain? A drizzly bear.",
        "Why was the math book sad after winning the lottery? Because it realized it had too many problems to solve!",
        "How do you make a tissue dance? You put a little boogie in it!",
        "Why did the scarecrow become a fashion model? Because he was outstanding in his field and had a great sense of straw-ma!",
        "Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them.",
        "What did the zero say to the eight? Nice belt!",
        "Why did the chicken join a band? Because it had the drumsticks!",
        "What's a pirate's favorite letter? You'd think it's 'R,' but it's actually the 'C' (sea) they love.",
        "Why don't scientists trust atoms that sing? Because they might be unstable!",
        "What do you call a bear that's stuck in traffic? A grizzly commuter.",
        "Why did the bicycle fall over? Because it was tired of the same old cycle!",
        "Why did the computer apply for a job? It wanted to have more bytes in its life.",
        "How do you organize a space party on the sun? You don't; it's too hot to handle!",
        "Why did the tomato turn red? Because it saw the salad dressing, and it got embarrassed!",
        "What do you call a group of musical whales who love classical music? An orca-stra-phonic ensemble!",
        "How do you organize a space party on Pluto? You send out cold invitations!",
        "Why did the scarecrow win an award? Because he was the best at standing still!",
        "Why don't skeletons fight each other? They don't have the guts or the stomach for it!",
        "What do you call a pig that knows karate? Porkchop!",
        "Why did the scarecrow win an award? Because he was outstanding at his job, even in a crop-up!",
        "What do you get when you cross a snowman and a vampire? Frostbite, with a craving for cold blood!",
        "What did the janitor say when he jumped out of the closet? 'Supplies!'",
        "Why did the scarecrow become a gardener? Because he wanted to put down roots!",
        "How do you make a lemon drop? Just let it fall!",
        "What do you call a can opener that doesn't work? A can't opener!",
        "Why did the bicycle stand up by itself? Because it was two-tired of lying down!",
        "What's green and sings? Elvis Parsley!",
        "Why don't scientists trust atoms that are late? Because they make up excuses!",
        "How do you organize a space party on the moon? You lunar-gize it!",
        "What did the astronaut use to keep his pants up? An asteroid belt!",
        "Why did the golfer bring two pairs of pants? In case he got a hole-in-one!",
        "What's a vampire's favorite fruit? A blood orange!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "Why did the scarecrow become a successful politician? Because he was outstanding in his field!",
        "Why don't scientists trust atoms? Because they make up everything!",
        "Why did the math book look sad? Because it had too many problems!",
        "How do you make holy water? You boil the hell out of it!",
        "What do you call a fish with no eyes? Fsh!",
        "What do you call a fake noodle? An impasta!",
    ];
?>